export const GET_CURIOSITY_PICS = 'GET_CURIOSITY_PICS';
export const GET_OPPORTUNITY_PICS = 'GET_OPPORTUNITY_PICS';
export const GET_SPIRIT_PICS = 'GET_SPIRIT_PICS';

//FILTERS
export const FILTER_BY_CAMERAS_CURIOSITY = 'FILTER_BY_CAMERAS_CURIOSITY';

//SELECT ROVER
export const SELECT_CURIOSITY = 'SELECT_CURIOSITY';
export const SELECT_OPPORTUNITY = 'SELECT_OPPORTUNITY';
export const SELECT_SPIRIT = 'SELECT_SPIRIT';
